<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'apimatic\\jsonmapper\\' => array($vendorDir . '/apimatic/jsonmapper/src'),
    'Unirest\\' => array($vendorDir . '/apimatic/unirest-php/src'),
    'Twilio\\' => array($vendorDir . '/twilio/sdk/src/Twilio'),
    'Symfony\\Polyfill\\Php80\\' => array($vendorDir . '/symfony/polyfill-php80'),
    'Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'Symfony\\Polyfill\\DeepClone\\' => array($vendorDir . '/symfony/polyfill-deepclone'),
    'Symfony\\Polyfill\\Ctype\\' => array($vendorDir . '/symfony/polyfill-ctype'),
    'Symfony\\Contracts\\Service\\' => array($vendorDir . '/symfony/service-contracts'),
    'Symfony\\Contracts\\Cache\\' => array($vendorDir . '/symfony/cache-contracts'),
    'Symfony\\Component\\VarExporter\\' => array($vendorDir . '/symfony/var-exporter'),
    'Symfony\\Component\\Process\\' => array($vendorDir . '/symfony/process'),
    'Symfony\\Component\\HttpFoundation\\' => array($vendorDir . '/symfony/http-foundation'),
    'Symfony\\Component\\Cache\\' => array($vendorDir . '/symfony/cache'),
    'Square\\' => array($vendorDir . '/square/square/src'),
    'Spatie\\TemporaryDirectory\\' => array($vendorDir . '/spatie/temporary-directory/src'),
    'ShipStream\\FedEx\\' => array($vendorDir . '/shipstream/fedex-rest-sdk/src'),
    'Saloon\\RateLimitPlugin\\Tests\\' => array($vendorDir . '/saloonphp/rate-limit-plugin/tests'),
    'Saloon\\RateLimitPlugin\\' => array($vendorDir . '/saloonphp/rate-limit-plugin/src'),
    'Saloon\\' => array($vendorDir . '/saloonphp/saloon/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/src'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-factory/src', $vendorDir . '/psr/http-message/src'),
    'Psr\\Http\\Client\\' => array($vendorDir . '/psr/http-client/src'),
    'Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'Psr\\Cache\\' => array($vendorDir . '/psr/cache/src'),
    'PhpOption\\' => array($vendorDir . '/phpoption/phpoption/src/PhpOption'),
    'PapayasauceClasses\\' => array($baseDir . '/PapayasauceClasses'),
    'PHPMailer\\PHPMailer\\' => array($vendorDir . '/phpmailer/phpmailer/src'),
    'GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
    'GrahamCampbell\\ResultType\\' => array($vendorDir . '/graham-campbell/result-type/src'),
    'FFMpeg\\' => array($vendorDir . '/php-ffmpeg/php-ffmpeg/src/FFMpeg'),
    'Evenement\\' => array($vendorDir . '/evenement/evenement/src'),
    'Dotenv\\' => array($vendorDir . '/vlucas/phpdotenv/src'),
    'Core\\' => array($vendorDir . '/apimatic/core/src'),
    'CoreInterfaces\\' => array($vendorDir . '/apimatic/core-interfaces/src'),
    'ClickSend\\' => array($vendorDir . '/clicksend/clicksend-php/lib'),
    'Alchemy\\BinaryDriver\\' => array($vendorDir . '/php-ffmpeg/php-ffmpeg/src/Alchemy/BinaryDriver'),
);
