<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitad427cee1dc2b3162fc8ae2206639041
{
    public static $files = array (
        '6e3fae29631ef280660b3cdad06f25a8' => __DIR__ . '/..' . '/symfony/deprecation-contracts/function.php',
        '7b11c4dc42b3b3023073cb14e519683c' => __DIR__ . '/..' . '/ralouphie/getallheaders/src/getallheaders.php',
        '37a3dc5111fe8f707ab4c132ef1dbc62' => __DIR__ . '/..' . '/guzzlehttp/guzzle/src/functions_include.php',
        '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => __DIR__ . '/..' . '/symfony/polyfill-mbstring/bootstrap.php',
        'deecf9d6b2672fb73429f9b28fdee35f' => __DIR__ . '/..' . '/symfony/polyfill-deepclone/bootstrap.php',
        '320cde22f66dd4f5d3fd621d3e88b98f' => __DIR__ . '/..' . '/symfony/polyfill-ctype/bootstrap.php',
        'a4a119a56e50fbb293281d9a48007e0e' => __DIR__ . '/..' . '/symfony/polyfill-php80/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'a' =>
        array (
            'apimatic\\jsonmapper\\' => 20,
        ),
        'U' =>
        array (
            'Unirest\\' => 8,
        ),
        'T' =>
        array (
            'Twilio\\' => 7,
        ),
        'S' =>
        array (
            'Symfony\\Polyfill\\Php80\\' => 23,
            'Symfony\\Polyfill\\Mbstring\\' => 26,
            'Symfony\\Polyfill\\DeepClone\\' => 27,
            'Symfony\\Polyfill\\Ctype\\' => 23,
            'Symfony\\Contracts\\Service\\' => 26,
            'Symfony\\Contracts\\Cache\\' => 24,
            'Symfony\\Component\\VarExporter\\' => 30,
            'Symfony\\Component\\Process\\' => 26,
            'Symfony\\Component\\HttpFoundation\\' => 33,
            'Symfony\\Component\\Cache\\' => 24,
            'Square\\' => 7,
            'Spatie\\TemporaryDirectory\\' => 26,
            'ShipStream\\FedEx\\' => 17,
            'Saloon\\RateLimitPlugin\\Tests\\' => 29,
            'Saloon\\RateLimitPlugin\\' => 23,
            'Saloon\\' => 7,
        ),
        'P' =>
        array (
            'Psr\\Log\\' => 8,
            'Psr\\Http\\Message\\' => 17,
            'Psr\\Http\\Client\\' => 16,
            'Psr\\Container\\' => 14,
            'Psr\\Cache\\' => 10,
            'PhpOption\\' => 10,
            'PapayasauceClasses\\' => 19,
            'PHPMailer\\PHPMailer\\' => 20,
        ),
        'G' =>
        array (
            'GuzzleHttp\\Psr7\\' => 16,
            'GuzzleHttp\\Promise\\' => 19,
            'GuzzleHttp\\' => 11,
            'GrahamCampbell\\ResultType\\' => 26,
        ),
        'F' =>
        array (
            'FFMpeg\\' => 7,
        ),
        'E' =>
        array (
            'Evenement\\' => 10,
        ),
        'D' =>
        array (
            'Dotenv\\' => 7,
        ),
        'C' =>
        array (
            'Core\\' => 5,
            'CoreInterfaces\\' => 15,
            'ClickSend\\' => 10,
        ),
        'A' =>
        array (
            'Alchemy\\BinaryDriver\\' => 21,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'apimatic\\jsonmapper\\' =>
        array (
            0 => __DIR__ . '/..' . '/apimatic/jsonmapper/src',
        ),
        'Unirest\\' =>
        array (
            0 => __DIR__ . '/..' . '/apimatic/unirest-php/src',
        ),
        'Twilio\\' =>
        array (
            0 => __DIR__ . '/..' . '/twilio/sdk/src/Twilio',
        ),
        'Symfony\\Polyfill\\Php80\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php80',
        ),
        'Symfony\\Polyfill\\Mbstring\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-mbstring',
        ),
        'Symfony\\Polyfill\\DeepClone\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-deepclone',
        ),
        'Symfony\\Polyfill\\Ctype\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-ctype',
        ),
        'Symfony\\Contracts\\Service\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/service-contracts',
        ),
        'Symfony\\Contracts\\Cache\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/cache-contracts',
        ),
        'Symfony\\Component\\VarExporter\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/var-exporter',
        ),
        'Symfony\\Component\\Process\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/process',
        ),
        'Symfony\\Component\\HttpFoundation\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/http-foundation',
        ),
        'Symfony\\Component\\Cache\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/cache',
        ),
        'Square\\' =>
        array (
            0 => __DIR__ . '/..' . '/square/square/src',
        ),
        'Spatie\\TemporaryDirectory\\' =>
        array (
            0 => __DIR__ . '/..' . '/spatie/temporary-directory/src',
        ),
        'ShipStream\\FedEx\\' =>
        array (
            0 => __DIR__ . '/..' . '/shipstream/fedex-rest-sdk/src',
        ),
        'Saloon\\RateLimitPlugin\\Tests\\' =>
        array (
            0 => __DIR__ . '/..' . '/saloonphp/rate-limit-plugin/tests',
        ),
        'Saloon\\RateLimitPlugin\\' =>
        array (
            0 => __DIR__ . '/..' . '/saloonphp/rate-limit-plugin/src',
        ),
        'Saloon\\' =>
        array (
            0 => __DIR__ . '/..' . '/saloonphp/saloon/src',
        ),
        'Psr\\Log\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/log/src',
        ),
        'Psr\\Http\\Message\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/http-factory/src',
            1 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
        'Psr\\Http\\Client\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/http-client/src',
        ),
        'Psr\\Container\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/container/src',
        ),
        'Psr\\Cache\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/cache/src',
        ),
        'PhpOption\\' =>
        array (
            0 => __DIR__ . '/..' . '/phpoption/phpoption/src/PhpOption',
        ),
        'PapayasauceClasses\\' =>
        array (
            0 => __DIR__ . '/../..' . '/PapayasauceClasses',
        ),
        'PHPMailer\\PHPMailer\\' =>
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
        'GuzzleHttp\\Psr7\\' =>
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/psr7/src',
        ),
        'GuzzleHttp\\Promise\\' =>
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/promises/src',
        ),
        'GuzzleHttp\\' =>
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/guzzle/src',
        ),
        'GrahamCampbell\\ResultType\\' =>
        array (
            0 => __DIR__ . '/..' . '/graham-campbell/result-type/src',
        ),
        'FFMpeg\\' =>
        array (
            0 => __DIR__ . '/..' . '/php-ffmpeg/php-ffmpeg/src/FFMpeg',
        ),
        'Evenement\\' =>
        array (
            0 => __DIR__ . '/..' . '/evenement/evenement/src',
        ),
        'Dotenv\\' =>
        array (
            0 => __DIR__ . '/..' . '/vlucas/phpdotenv/src',
        ),
        'Core\\' =>
        array (
            0 => __DIR__ . '/..' . '/apimatic/core/src',
        ),
        'CoreInterfaces\\' =>
        array (
            0 => __DIR__ . '/..' . '/apimatic/core-interfaces/src',
        ),
        'ClickSend\\' =>
        array (
            0 => __DIR__ . '/..' . '/clicksend/clicksend-php/lib',
        ),
        'Alchemy\\BinaryDriver\\' =>
        array (
            0 => __DIR__ . '/..' . '/php-ffmpeg/php-ffmpeg/src/Alchemy/BinaryDriver',
        ),
    );

    public static $prefixesPsr0 = array (
        'R' =>
        array (
            'Rs\\Json' =>
            array (
                0 => __DIR__ . '/..' . '/php-jsonpointer/php-jsonpointer/src',
            ),
        ),
    );

    public static $classMap = array (
        'Attribute' => __DIR__ . '/..' . '/symfony/polyfill-php80/Resources/stubs/Attribute.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'DeepClone\\ClassNotFoundException' => __DIR__ . '/..' . '/symfony/polyfill-deepclone/Resources/stubs/ClassNotFoundException.php',
        'DeepClone\\NotInstantiableException' => __DIR__ . '/..' . '/symfony/polyfill-deepclone/Resources/stubs/NotInstantiableException.php',
        'PhpToken' => __DIR__ . '/..' . '/symfony/polyfill-php80/Resources/stubs/PhpToken.php',
        'Stringable' => __DIR__ . '/..' . '/symfony/polyfill-php80/Resources/stubs/Stringable.php',
        'UnhandledMatchError' => __DIR__ . '/..' . '/symfony/polyfill-php80/Resources/stubs/UnhandledMatchError.php',
        'ValueError' => __DIR__ . '/..' . '/symfony/polyfill-php80/Resources/stubs/ValueError.php',
        '©' => __DIR__ . '/..' . '/symfony/cache/Traits/ValueWrapper.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitad427cee1dc2b3162fc8ae2206639041::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitad427cee1dc2b3162fc8ae2206639041::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInitad427cee1dc2b3162fc8ae2206639041::$prefixesPsr0;
            $loader->classMap = ComposerStaticInitad427cee1dc2b3162fc8ae2206639041::$classMap;

        }, null, ClassLoader::class);
    }
}
